esphome:
  name: led-panel-1
  friendly_name: led-panel-1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "sT+stO/8tfhAWH2L7XIa8Nf529o5VLHbrThBNG7HxU8="

ota:
  - platform: esphome
    password: "251f9a2545d330bd0c3ac82d81daec81"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led-Panel-1 Fallback Hotspot"
    password: "JO2JHW70h7Tn"

captive_portal:

# The following lines are the important part of the configuration
# Example GPIO configuration for LED outputs
output:
  - platform: ledc
    pin: 9
    id: gpio_9
  - platform: ledc
    pin: 8
    id: gpio_8
# Example GPIO configuration for buttons
light:
  - platform: monochromatic
    output: gpio_9
    name: "Cool White"
  - platform: monochromatic
    output: gpio_8
    name: "Warm White"